name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd ../

      - name: Install dependencies
        run: pip install -r req.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name NBP_Report main.py

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nbp_report
          path: dist/NBP_Report.exe
