name: Publish Single-File App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change working directory
        working-directory: ./

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build single-file app
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py --name NBP_Report.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: single-file-app
          path: dist/NBP_Report.exe
